version: '3.9'

services:
  postgres:
    image: postgres:17-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=prisma
      - POSTGRES_USER=prisma
      - POSTGRES_DB=next-trello

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "9090:8080"

volumes:
  dbdata:
